apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-q6xg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-q6xg
    app.kubernetes.io/part-of: tkrw-pr714-0075-0038-app
  name: devfile-sample-q6xg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-q6xg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-q6xg
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0038-tenant/tkrw-pr714-0075-0038-app/devfile-sample-q6xg@sha256:055bf183411cdb3685534befd038575dd0af7e559c432f4533da40e03df0ad28
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
